### ISSUE TITLE
Metadados - IPTU

### ISSUE THREAD

**Issue by luiz-dejesus** [geoinfo-smdu/Abrindo-IPTU-R#3]
Olá @stees, tudo bem?

Muito bacana esse seus estudos iniciais dos dados de IPTU. Valeu por compartilhar !

Uma pergunta: Você tem o descritivo dos campos dos dados de IPTU (os famosos metadados, hehe).
Se não, tem alguma idéia de onde eu posso encontrar ou para quem eu posso perguntar?

Muito obrigado!

**Comment by stees** [comment]
Oi @luiz-dejesus! Fico feliz que tenha achado interessante.

No [GeoSampa](http://geosampa.prefeitura.sp.gov.br/PaginasPublicas/_SBC.aspx), se for no canto superior direito em "Acessar metadados", você vai ter acesso a uma planilha em que uma das abas contém exatamente o descritivo dos campos!

Mais pra frente vamos formalizar melhor internamente esse processamento do IPTU, e aí pretendemos deixar esses dados todos bem à mostra no leiame.

Espero ter ajudado!

**Comment by luiz-dejesus** [comment]
Olá @stees ! Mto top! Muitíssimo obrigado pela ajuda! Abs.
